name: Build and Push to BrowserFS-builds

on:
  push:
    branches:
      - v1.x
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: pnpm/action-setup@v4
        with:
            version: 9
      - name: Clone BrowserFS-builds repository
        uses: actions/checkout@v4
        with:
          path: ./BrowserFS-builds
          token: ${{ secrets.PAT }}
          repository: LosersUnited/BrowserFS-builds
      - run: |
          ls ./BrowserFS-builds/dist
      - name: Move dist from builds
        run: |
          mv ./BrowserFS-builds/dist ./dist
      - run: |
          ls ./dist
      - name: Install dependencies and build
        run: |
          pnpm install
      - name: Move dist to builds
        run: |
          rm -rf ./BrowserFS-builds/dist
          mv ./dist ./BrowserFS-builds/dist
      - run: |
          ls ./BrowserFS-builds/dist
      # - uses: EndBug/add-and-commit@v9
      #   with:
      #     cwd: './BrowserFS-builds'
      #     default_author: github_actions
      #     message: 'Automatic build based on ${{ steps.commit.outputs.hash }}'
      - run: |
          cd ./BrowserFS-builds
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatic build based on ${{ steps.commit.outputs.hash }}"
          git push
